### ISSUE TITLE
handle TODOS in shared_utils.js

### ISSUE THREAD

**Issue by mmmaaatttttt** [rithmschool/numbers_api#17]
Let's also format the code and do a general refactor:
https://github.com/rithmschool/numbers_api/blob/master/public/js/shared_utils.js

Edit: estimated 2 points

**Comment by Nalipp** [comment]
This pr should remove the TODO's from data.js.
For each TODO we can do one of three things.

Update the code as requested
Create a new issue
Delete the TODO if it is no longer relevant
