### ISSUE TITLE
Readme audit.

### ISSUE THREAD

**Issue by mmmaaatttttt** [rithmschool/numbers_api#18]
The README needs to have line breaks between all section headings, otherwise the markdown won't get parsed correctly. Here's an example (we shouldn't see backticks around `json`, for example):

<img width="951" alt="Screen Shot 2020-06-15 at 1 37 35 PM" src="https://user-images.githubusercontent.com/3916770/84704768-2c404080-af0f-11ea-9f52-5f8cbc335416.png">

**Comment by stephanedreyfus** [comment]
👍

**Comment by mmmaaatttttt** [comment]
closed by #27
