### ISSUE TITLE
Open source documentation / guidelines

### ISSUE THREAD

**Issue by mmmaaatttttt** [rithmschool/numbers_api#4]
This project needs some standard open-source documentation. Including:

- [x] Code of conduct
- [x] Contribution guidelines
- [ ] changelog
- [x] License (MIT https://opensource.org/licenses/MIT)
- [x] pull request template
- [x] issue template 

for the last two, see https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates

**Comment by mmmaaatttttt** [comment]
Hey @silasburger -- I think this should be higher priority, since it would be great to have the PR template as these PRs start coming in. Do you want to work on this, either by yourself or with @maxnawa31?

**Comment by silasburger** [comment]
@mmmaaatttttt @maxnawa31 

I would be happy with work on it with Max. I can spend some time after 5 today getting started on it. I'll reach out to Max on slack when I start. Also since it is high priority, if I'm lagging please get some others involved.

**Comment by mmmaaatttttt** [comment]
I'm not trying to pressure you, nothing here is truly urgent :) i just noticed that Roni mentioned PR tmeplated in her code review, and I agree that it would be nice to standardize PRs sooner rather than later. but no rush!

**Comment by silasburger** [comment]
Okay, sure I'll focus on that piece first :)

**Comment by maxnawa31** [comment]
Hey @silasburger ,
let me know which of the above checkboxes you would like to take on and I could take on the
remaining ones.

**Comment by maxnawa31** [comment]
hello @silasburger ,

just wondering if you started on any of the above checkboxes yet? just so were not working on the same ones.

Best,
Max
