### ISSUE TITLE
Remove document.write, jsonp

### ISSUE THREAD

**Issue by Nalipp** [rithmschool/numbers_api#50]
**Problem description**:  
  The original docs reference document.write, and jsonp.  
  These features are outdated and likely need to be removed from the project.

**Suggested solution**:  
  Remove this functionality from the codebase and update the docs.

**Comment by mmmaaatttttt** [comment]
Even better, if someone uses the write feature, let's modify the response to send a warning along with the data about why using this feature is not a good idea (google XSS document.write). Not sure how much sanitizing of the data we're doing on the backend to prevent xss.
