### ISSUE TITLE
Modernize fact.js

### ISSUE THREAD

**Issue by mmmaaatttttt** [rithmschool/numbers_api#58]
**Problem description**:

This file needs a fresh coat of paint: https://github.com/rithmschool/numbers_api/blob/master/models/fact.js

**Suggested solution**:

ES2015 refactor, no `var` keywords, address the todos, etc.

**Comment by DevinLeamy** [comment]
Hi. Good issue, code seems dated.... I'm new to the project but this seems to be my speed! Expect a PR! 👍

**Comment by mmmaaatttttt** [comment]
Hi Devin, thanks for your interest. We're not accepting outside PRs for the next three weeks while students in our current cohort spend time working on these issues. If the issue is still open three weeks from now, we'd welcome your contribution.

**Comment by DevinLeamy** [comment]
Okay, no worries. Thanks for the heads up
